# Copyright © 2025 Devin B. Royal. All Rights Reserved.
# Project: M3hl@n! Unified Build System (Original IP).
# SPDX-License-Identifier: LicenseRef-M3hlan-Enterprise
.PHONY: all init resolve build test release

all: build

init:
	@./build.sh init

resolve:
	@./build.sh resolve

build:
	@./build.sh build

test:
	@./build.sh test

release:
	@./build.sh release


# Copyright © 2025 Devin B. Royal. All Rights Reserved.